title = "Wood from Trees"
baseURL = "/"
publishDir = "public"
# tags = ["portfolio", "web design", "blog"]
languageCode = "en-GB"
config = "config.toml"
theme = "wood_theme"
# canonifyURLS = true
# googleAnalytics = ""
# disqusShortname = ""
# disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies
[Params]
    herotitle = "This is wood from trees."

# [Params]
#     tagline = "Green woodcraft by Zach Beauvais"
#     author = "Zach Beauvais"
#     description = ""
#     logoBig = "/images/osprey-logo.png"
#     logoSmall = "/images/osprey-logo.png"
#     favicon = "favicon.ico"
#     opengraphImage = "/images/osprey.png"
#     twitter = ""
#     linkedin = ""
#     github = ""
#     email = ""
#     googleTagManager = ""
#     highlightJS = true
#     copyright = true
#     credit = true
#     customCSS = false
#     cacheBustCSS = false
#     cacheBustJS = false
#     ajaxFormspree = true

# [[menu.main]]
#     name = "About"
#     url  = "/#about"
#     weight = 1
# [[menu.main]]
#     name = "Products"
#     url  = "/products"
#     weight = 2
# [[menu.main]]
#     name = "Blog"
#     url  = "/blog"
#     weight = 3
# # [[menu.main]]
# #     name = "Contact"
# #     url  = "/#contact"
# #     weight = 4
