title = "Zach Beauvais – writer, wood worker, word strategist"
baseURL = "/"
publishDir = "public"
# tags = ["portfolio", "web design", "blog"]
languageCode = "en-GB"
config = "config.toml"
theme = "zb"
canonifyURLS = false
# relativeURLs = true
# googleAnalytics = "UA-107957056-1"
# disqusShortname = ""
# disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies
[Permalinks]
    post = "/:section/:title/"
[Params]
    subtitle = "Writer, wood worker, word strategist"
    owner = "Zach Beauvais"
[taxonomies]
    tag = "tags"
    category = "categories"