title = "Zach Beauvais – coffee drinker, writer, and content strategist"
baseURL = "/"
publishDir = "public"
# tags = ["portfolio", "web design", "blog"]
languageCode = "en-GB"
config = "config.toml"
theme = "zb"
canonifyURLS = false
relativeURLs = true
# googleAnalytics = "UA-107957056-1"
# disqusShortname = ""
# disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies
[Params]
    herotitle = "blogging perspective"