# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "zb"
license = "MIT"
licenselink = "https://github.com/beauvais/new_home/blob/master/LICENSE.md"
description = "A theme for a blog  using the Bulma CSS framework"
homepage = "https://github.com/beauvais/new_home"
tags = [blog, personal,, Bulma, SASS]
features = [Bulma, scss, SASS]
min_version = "0.25.1"

[author]
  name = "Zach Beauvais"
  homepage = "https://zachbeauvais.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
